### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by talentlessguy** [mailersend/mailersend-nodejs#10]
Would be cool for this library to have typings in a `d.ts` file so it would have a better editor support

**Comment by teamzz111** [comment]
Totally agree.

**Comment by joshxyzhimself** [comment]
Also looking for this, thank you.

**Comment by fredsossa1** [comment]
Hi, do we have any status updates on this?

**Comment by me-shaon** [comment]
Hi,
I started work on it: https://github.com/mailersend/mailersend-nodejs/pull/20 but got occupied with other priorities. If anyone wants to make some contribution, that'd be appreciated. 🙏

**Comment by fosron** [comment]
Hacktoberfest community! We would really welcome input from you on this issue, either adding a dynamic way to generate typings, or even migrating the code base to TypeScript!

**Comment by 8thblock** [comment]
1. Definitely use TypeSript
2. Also build ESM modules. CJS is slowly going away & not standards compliatn

**Comment by fosron** [comment]
@8thblock that would be wonderful! Can we get in touch and tinker out details? :)

**Comment by 8thblock** [comment]
Email sent

**Comment by opheus2** [comment]
Hi @buzzb0x, We are currently working on this, and we would update soon.

**Comment by GerryWilko** [comment]
I've written a `.d.ts` file for the mailersend package whilst we wait for official typescript support. This covers the basics for emails. Just need to create a file called something like `mailersend-t.d.ts` in the root of your project and you should be good to go.

``` typescript
declare module 'mailersend' {
  class MailerSend{
    constructor(config: { api_key: string })
    send(email: EmailParams): Promise<Response>
  }

  export class Recipient {
    constructor(email: string, name: string)
  }

  export interface Personalization {
    email: string,
    data: Record<string, string>
  }

  export class EmailParams {
    setFrom(from: string): EmailParams
    setFromName(name: string): EmailParams
    setRecipients(recipients: Recipient[]): EmailParams
    setSubject(subject: string): EmailParams
    setTemplateId(templateId: string): EmailParams
    setPersonalization(personalizations: Personalization[]): EmailParams
  }

  export default MailerSend
}
```

**Comment by GerryWilko** [comment]
@opheus2 it looks like you guys are sticking with cjs modules and JS with typings file from what I can see on the branch `add-typings`. Would it not be quicker to just transform the whole repo to Typescript? Any dependencies that need CJS can always build their own version and it would be great to build it to es modules format.

**Comment by opheus2** [comment]
Hey @GerryWilko yes and no. Converting to full TS isn't exactly faster, however converting the whole codebase to TS is the new goal.

**Comment by GerryWilko** [comment]
@opheus2 Sorry yes I probably meant better rather than quicker. That's great news. Hopefully anyone who gets stuck on a TS project for now can get going with my Typings file.

**Comment by opheus2** [comment]
#54 has the complete revamp to TS. Release of TS version soon... 
WIP
