### ISSUE TITLE
Add changelog and/or tagged releases

### ISSUE THREAD

**Issue by hacknug** [mailersend/mailersend-nodejs#18]
This is a must if we're expected to keep our dependency up to date (of course we are).

It can probably be automatically created from commit messages. Ideally it would allow things like Dependabot/Renovate/Depfu to source this changelog to let maintainers know what changed between versions.

**Comment by me-shaon** [comment]
Thanks for the suggestion. We'll do it soon.

**Comment by hacknug** [comment]
Awesome 🙌  Thank you!

**Comment by me-shaon** [comment]
@hacknug we've created our first release with tag: https://github.com/mailersend/mailersend-nodejs/releases/tag/v1.1.1 from the current state of the repository.
From now on, we'll create a tagged release with changelogs for our next releases.
