### ISSUE TITLE
Can't send emails if variables.*.substitutions.*.value is an empty string

### ISSUE THREAD

**Issue by haihninit** [mailersend/mailersend-nodejs#28]
I'm trying to send an email using a `POST` request to `https://api.mailersend.com/v1/email`

Here is the `variables` section of the request body:

```
    "variables": [
        {
            "email": "myemail@domain.com",
            "substitutions": [
                {
                    "var": "name",
                    "value": ""
                }
            ]
        }
    ]
```

And here is the response

`422 Unprocessable Entity`

```
{
    "message": "The given data was invalid.",
    "errors": {
        "variables.0.substitutions.0.value": [
            "The variables.0.substitutions.0.value field is required."
        ]
    }
}
```

Is there any way to make **variables.0.substitutions.0.value** be optional? Because sometimes I don't need the value and will use some conditions in the template to handle if the value is empty

**Comment by ibrahimyaacob92** [comment]
How did you have the access to the message & error objects ?

**Comment by JuliusB** [comment]
What if you don't send substitution at all instead of sending an empty value?

**Comment by fosron** [comment]
This has been fixed on API side. `value` must still be present, but can be an empty string or `null`
