### ISSUE TITLE
Node.js npm

### ISSUE THREAD

**Issue by LyrranKelmalu** [mailersend/mailersend-nodejs#55]
Hello, 

I used node.js example by implemented MailerSend class. I copied code from documentation, but when I create new class with api_key as parameters and save it to variable that, so that variable doesn't have "send" method. 

And I didn't found that method in node_modules/mailersend folder. I am doing something wrong? 

Of course I can create request via axios, but thought to ask you guys first.

**Comment by opheus2** [comment]
Hi, @LyrranKelmalu I need more context... can you paste the code you built without your API key
