### ISSUE TITLE
Problem in TypeScript using NPM package

### ISSUE THREAD

**Issue by pmtascencao** [mailersend/mailersend-nodejs#60]
Hey guys, 

When using the NPM package, I'm having an error where when I set personalizations like this:

`.setPersonalization(personalization)`

The error is caused because my object is something like this:

```
    const personalization = [
      {
        email: 'your@client.com',
        data: {
          name: 'Test Value',
          order: {
            total: '',
            number: '',
            shipping: '',
            subtotal: '',
            createdAt: '',
          },
        },
      },
    ];
```

And the personalization interface says that data has a string key and a string value:
 `export interface Personalization {
    email: string;
    data: {
        [key: string]: string;
    };
}
` 

Can we fix this? Do u want any help?

**Comment by fosron** [comment]
@pmtascencao You are always free to submit a PR 🙇 Otherwise it will take a little bit of time for our team to fix it.

**Comment by opheus2** [comment]
@pmtascencao issue has been resolved

**Comment by pmtascencao** [comment]
@opheus2 Thanks a lot for the quick fix :+1:   @fosron next time I'll do a PR instead!
