### ISSUE TITLE
Add the "Get API quota" endpoint

### ISSUE THREAD

**Issue by Agathe-Brusset** [mailersend/mailersend-nodejs#72]
- [ ] Add the [Get API quota](https://develop.developers-mailersend.pages.dev/api/v1/other-endpoints.html) endpoint
- [ ] Add it to the README
- [ ] Add it to the TOC.

**Comment by doobas** [comment]
Maybe it's better to add this info into response headers? Same as we return `x-ratelimit-limit`, `x-ratelimit-remaining`

**Comment by Agathe-Brusset** [comment]
We do already have this endpoint, this issue is about the NodeJS SDK. The header already has the information, but it's not enough and we decided to create an endpoint for this.
