### ISSUE TITLE
Add the priority parameter to the inbound route endpoints

### ISSUE THREAD

**Issue by Agathe-Brusset** [mailersend/mailersend-nodejs#81]
We have a new parameter called "inbound_priority" on our Inbound Routes. This parameter allows our users to create multiple inbound routes per inbound subdomain. Each one of the routes will be processed in a descending order. Values can be between 0 and 100. 0 has more importance than 100.

- [ ] Add the "inbound_priority" parameter on the "[Add an inbound route](https://developers.mailersend.com/api/v1/inbound.html#add-an-inbound-route)" endpoint, on the request and the response.
- [ ] Add the "inbound_priority" parameter on the "[Get a list of inbound routes](https://developers.mailersend.com/api/v1/inbound.html#get-a-list-of-inbound-routes)" endpoint, on the request and the response.
- [ ] Add the "inbound_priority" parameter on the "[Get a single inbound route](https://developers.mailersend.com/api/v1/inbound.html#get-a-single-inbound-route)" endpoint, on the request and the response.
- [ ] Add the "inbound_priority" parameter on the "[Update an inbound route](https://developers.mailersend.com/api/v1/inbound.html#update-an-inbound-route)" endpoint, on the request and the response.

**Comment by opheus2** [comment]
I had done this already on https://github.com/mailersend/mailersend-nodejs/pull/78 did I miss something

**Comment by opheus2** [comment]
I think I forgot to close the issue 😮‍💨
